github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/123movies-downloader",
"https://serp.co/products/123movies-downloader",
"https://store.serp.co/product-details/product/123movies-downloader",
]
